version: '3.8'

services:

    back:
        restart: always
        build: .
        ports:
          - "8020:8020"
        command: >
            bash -c "python manage.py makemigrations
            &&python manage.py migrate
            &&python manage.py runserver 0.0.0.0:8020"
        volumes:
            - .:/app
